
services:
  server:
    image: nginx
    environment:
      VIRTUAL_HOST: deploy.khalil.ink
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: deploy.khalil.ink
      LETSENCRYPT_EMAIL: mail@khalil.ink
    networks:
      - nginx-proxy



networks:
  nginx-proxy:
    external: true