name: Deploy

on:
  push:
    branches:
      ['main']

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ls -al