name: Deploy

on:
  push:
    branches:
      ['main']

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: checking variable
        run:   echo "${{ secrets.SSH_PRIVATE_KEY }}" >> file && echo "${{ secrets.SSH_KEY }}" >> file && echo "${{ secrets.HOST }}" >> file

      - name: check file
        run: cat file

      - name: install ssh
        run: sudo apt upgrade && sudo apt install openssh-client

      - name: add ssh key
        run: mkdir .ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519 && echo "${{ secrets.SSH_KEY }}" > id_ed25519.pub



      - name: connect to server
        run: ssh ${{ secrets.HOST }}

      - name: create file
        run: cd /root && touch file

      - name: Check out repository code
        uses: actions/checkout@v4