name: Deploy

on:
  push:
    branches:
      ['main']

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: kickstart-s/deploy
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}