name: Deploy

on:
  push:
    branches:
      ['main']

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
      - name: create file
        run: cd /root && touch file
      - name: Check out repository code
        uses: actions/checkout@v4